<a href="https://colab.research.google.com/github/2303a51355/_10_Python-for-DataScience/blob/main/lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
add_result = np.add(A, B)
sub_result = np.subtract(A, B)
print("A:\n", A)
print("B:\n", B)
print("A + B:\n", add_result)
print("A - B:\n", sub_result)


A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
